
# CIFAR-10 + ViT-Tiny (MPS-ready)
model: vit_tiny
dataset: cifar10
data_dir: ./data
epochs: 5
batch_size: 128
lr: 0.0005
weight_decay: 0.05
workers: 4
no_pretrained: false
grad_clip: 0.0
benchmark: true
export_onnx: "outputs/models/vit_tiny_cifar10.onnx"
