name: Python CI

on:
  push:
    branches: [ main, master ]
    paths: ["**.py", "requirements*.txt", ".github/workflows/python-ci.yml"]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      PYTHONHASHSEED: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff (lint)
        run: ruff check .
      - name: Mypy (type-check)
        run: mypy .

      - name: Run tests (pytest)
        run: |
          mkdir -p .pytest-results
          pytest -q \
