name: Python CI

on:
  push:
    branches: [ main, master ]
    tags: ['v*.*.*']  # e.g. v1.0.0, v2.3.1
    paths: ["**.py", "requirements*.txt", ".github/workflows/python-ci.yml"]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      PYTHONHASHSEED: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff (lint)
        run: ruff check .

      - name: Run tests (pytest)
        run: |
          mkdir -p .pytest-results
          pytest -q \

      - name: Package source
        run: |
          mkdir -p artifacts
          git archive --format zip --output artifacts/source.zip HEAD
        if: startsWith(github.ref, 'refs/tags/')

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
